# Use root/example as user/password credentials

services:
  db:
    image: mysql
    restart: always
    env_file: .env
    ports:
      - ${MYSQL_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    # (this is just an example, not intended to be a production configuration)

